<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="API_suite" duration-ms="5714" started-at="2018-08-11T19:15:01Z" finished-at="2018-08-11T19:15:07Z">
    <groups>
    </groups>
    <test name="API_suite" duration-ms="5714" started-at="2018-08-11T19:15:01Z" finished-at="2018-08-11T19:15:07Z">
      <class name="com.qa.tests.PostCampaign">
        <test-method status="FAIL" signature="campaign()[pri:0, instance:com.qa.tests.PostCampaign@1068e947]" name="campaign" duration-ms="1207" started-at="2018-08-11T19:15:06Z" finished-at="2018-08-11T19:15:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [400]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.qa.tests.PostCampaign.campaign(PostCampaign.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- campaign -->
      </class> <!-- com.qa.tests.PostCampaign -->
      <class name="com.qa.util.TestUtil">
        <test-method status="PASS" signature="getAuth()[pri:0, instance:com.qa.util.TestUtil@2f8f5f62]" name="getAuth" is-config="true" duration-ms="4463" started-at="2018-08-11T19:15:01Z" finished-at="2018-08-11T19:15:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAuth -->
      </class> <!-- com.qa.util.TestUtil -->
    </test> <!-- API_suite -->
  </suite> <!-- API_suite -->
</testng-results>
